[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rcc-non-linear"
version = "0.1.0"
description = "Nonlinear analysis tools for RCC structures"
authors = [{ name = "Abinash Mandal" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "math"
    "numpy",
    "scipy",
    "matplotlib",
    "pandas"
]

[tool.setuptools]
packages = [
    "rcc_non_linear",
    "rcc_non_linear.concrete_models",
    "rcc_non_linear.concrete_models.data",
    "rcc_non_linear.moment_curvature",
    "rcc_non_linear.pushover",
    "rcc_non_linear.utils"
]

include-package-data = true

[tool.setuptools.package-data]
"rcc_non_linear.concrete_models.data" = ["*.csv"]

